#!/usr/bin/env python3
# transfer lammps dump file to POSCAR
# input fomat : lammps2poscar <filename> <step> <atom_type_1> <atom_type_2> <atom_type_3> ...
import sys
sys.path.append('/home/yangsun/git/pylib')
import MD

filename=sys.argv[1]
step=sys.argv[2]
leng=len(sys.argv)
ntype=[]
for i in range(1,leng-2): ntype.append(sys.argv[2+i])
print(ntype)
MD.lamp2poscar(filename,int(step),ntype)
